import Sound.Csound.Score

import Data.Monoid

score =
     F 1 0 4096 (GEN10 [1])

main = print $  Comment "Generated by Sound.Csound" 
             <> F 1 0 4096 (GEN10 [1])
             <> gensco 100
             
geni start freq = 
        let num   = 1
            dur   = 0.1
            amp   = 10000
            tbl   = 1
        in I num start dur [amp,freq,tbl]

gensco n = mconcat $ gensco' 0
  where gensco' i =
          if i > n
             then []
             else geni (i * 0.1) (220 + i * 10) : gensco' (i + 1)
           

           
